config/routes.rb
Rails.application.routes.draw do
  get 'tour_booking/:tour_package_id/tour_booker' => 'tour_booking#tour_booker', as: :tour_booker

  post 'tour_booking/:tour_package_id/tour_booker' => 'tour_booking#tour_booker_create', as: :tour_booker_create

  get 'tour_booking/:tour_package_id/tour_members' => 'tour_booking#tour_members', as: :tour_members

  post 'tour_booking/:tour_package_id/tour_members' => 'tour_booking#tour_member_create', as: :tour_member_create

  get 'tour_booking/:tour_package_id/tour_confirm' => 'tour_booking#tour_confirm', as: :tour_confirm

  post 'tour_booking/:tour_package_id/tour_confirm' => 'tour_booking#tour_confirm_done', as: :tour_confirm_done

  resources :tour_packages do
  	collection do
  		get "search"
  		get "filter"
  	end
  end
  resources :destinations
  devise_for :users

  authenticated :user do
    root 'tour_packages#index', as: :authenticated_root
  end

  root "tour_packages#index", as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour_booking.rb
class TourBooking < ApplicationRecord
  belongs_to :tour_package
  belongs_to :user
  has_many :passengers

  validates :name, presence: true, length: { minimum: 2 }
  validates :number_of_people, presence: true, numericality: { only_integer: true }

  def total_cost
  	(self.passengers.count+1) * self.tour_package.cost_per_person
  end
end

app/controllers/tour_booking_controller.rb
class TourBookingController < ApplicationController
	before_action :find_tour_package
	before_action :find_tour_booker_if_exist, :only => [:tour_booker_create]
	before_action :check_if_already_booked
	before_action :find_tour_booker, :only => [:tour_members,:tour_member_create,:tour_confirm,:tour_confirm_done]

  def tour_booker
  	unless (@tour_booking = @tour_package.tour_bookings.find_by_user_id(current_user))
  		@tour_booking = current_user.tour_bookings.new
  	end
  end

  def tour_booker_create
  	if @tour_booking
  		@tour_booking.update(tour_booking_params)
  	else
    	@tour_booking = @tour_package.tour_bookings.new(tour_booking_params)
  	end
    @tour_booking.user_id = current_user.id
    if @tour_booking.save
    	redirect_to tour_members_url(@tour_package.id)
    else
    	render "tour_booker"
    end
  end

  def tour_members
  	
  end

  def tour_member_create
  	@tour_booking.passengers.each do |p|
  		p.destroy
  	end
  	if params[:passenger][:name] and (params[:passenger][:name].size == (@tour_booking.number_of_people-1))
  		(@tour_booking.number_of_people-1).times do |i|
  			@tour_booking.passengers.create(name:params[:passenger][:name][i],age:params[:passenger][:age][i],gender:params[:passenger][:gender][i])
  		end
  		redirect_to tour_confirm_url(@tour_package.id)
  	else
  		render "tour_members"
  	end
  end

  def tour_confirm
  end

  def tour_confirm_done
  	if params[:confirmation] == "1"
  		@tour_booking.confirmation = true
  		@tour_booking.save
  		redirect_to @tour_package
  	else
  		render "tour_confirm"
  	end
  end

  private

  def find_tour_package
  	unless (@tour_package = TourPackage.find(params[:tour_package_id]))
  		redirect_to "/"
  	end
  end

  def tour_booking_params
	  params.require(:tour_booking).permit(:name, :contact, :address, :number_of_people)
  end

  def find_tour_booker_if_exist
  	@tour_booking = @tour_package.tour_bookings.find_by_user_id(current_user.id)
  end

  def check_if_already_booked
  	if @tour_package and find_tour_booker_if_exist and @tour_booking.confirmation
  		redirect_to @tour_package
  	end
  end

  def find_tour_booker
  	unless find_tour_booker_if_exist
  		redirect_to tour_booker_url(@tour_package.id)
  	end
  end
end

app/helpers/tour_booking_helper.rb
module TourBookingHelper
end

app/views/tour_booking/_form1.html.erb
<%= form_with(url: tour_booker_create_url(tour_package.id), method: :post, local: true) do |form| %>
  <div class="step_1">
    <% if tour_booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tour_booking.errors.count, "error") %> prohibited this tour_booking from being saved:</h2>

        <ul>
        <% tour_booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field "tour_booking[name]", :value => tour_booking.name ,id: :tour_booker_name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :contact %>
      <%= form.number_field "tour_booking[contact]", :value => tour_booking.contact ,id: :tour_booker_contact, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :address %>
      <%= form.text_area "tour_booking[address]", :value => tour_booking.address ,id: :tour_booker_address, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :number_of_people %>
      <%= form.number_field "tour_booking[number_of_people]", :value => tour_booking.number_of_people ,id: :tour_booker_number_of_people, :class => "form-control" %>
    </div>
    <div class="form-group text-center">
      <%= form.submit "Create Booker",:class => "btn btn-success" %>
    </div>
<% end %>
<div class="col-lg-12 text-center">
  <%= link_to 'Back', tour_package_path(@tour_package.id), :class => "btn btn-primary" %>
</div>

app/views/tour_booking/_form2.html.erb
<%= form_with(url: tour_member_create_url(tour_package.id), method: :post, local: true) do |form| %>
  <div class="step_2">
    <% if tour_booking.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tour_booking.errors.count, "error") %> prohibited this tour_booking from being saved:</h2>

        <ul>
        <% tour_booking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <% passengers = tour_booking.passengers %>
    <% (tour_booking.number_of_people-1).times do |p| %>
      <div class="passBox mb-10">
        <div class="h4 text-muted">Passenger #<%= p+2 %></div>
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field "passenger[name][]", :value => ((passengers.any? and passengers[p]) ? passengers[p].name : "") ,id: :passenger_name, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :age %>
          <%= form.number_field "passenger[age][]", :value => ((passengers.any? and passengers[p]) ? passengers[p].age : "") ,id: :passenger_age, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :gender %>
          <%= form.text_field "passenger[gender][]", :value => ((passengers.any? and passengers[p]) ? passengers[p].gender : "") ,id: :passenger_gender, :class => "form-control" %>
        </div>
      </div>
    <% end %>
    <div class="form-group text-center">
      <%= form.submit "Create Passengers",:class => "btn btn-success" %>
    </div>
<% end %>
<div class="col-lg-12 text-center">
  <%= link_to 'Back', tour_booker_path(@tour_package.id), :class => "btn btn-primary" %>
</div>

app/views/tour_booking/_form3.html.erb
<%= form_with(url: tour_confirm_done_url(tour_package.id), method: :post, local: true) do |form| %>
  <div class="step_3">
    <div class="passBox mb-10">
      <div class="h4 text-muted">Main Passenger #<%= 1 %></div>
      <div class="form-group">
        <label>Name:</label>
        <%= tour_booking.name %>
      </div>
      <div class="form-group">
        <label>Contact:</label>
        <%= tour_booking.contact %>
      </div>
      <div class="form-group">
        <label>Address:</label>
        <%= tour_booking.address %>
      </div>
    </div>
    <% tour_booking.passengers.each_with_index do |p,i| %>
      <div class="passBox mb-10">
        <div class="h4 text-muted">Passenger #<%= i+2 %></div>
        <div class="form-group">
          <label>Name:</label>
          <%= p.name %>
        </div>
        <div class="form-group">
          <label>Age:</label>
          <%= p.age %>
        </div>
        <div class="form-group">
          <label>Gender:</label>
          <%= p.gender %>
        </div>
      </div>
    <% end %>
    <div class="col-lg-12 padding-reset">
      <div class="passBox"><label>Total Cost:</label> <%= @tour_booking.total_cost %></div>
      <div class="pull-left"><%= form.check_box :confirmation, :class => "form-control", :required => true %> Confirm my tour</div>
    </div>
    <div class="form-group text-center">
      <%= form.submit "Confirm Tour",:class => "btn btn-success" %>
    </div>
<% end %>
<div class="col-lg-12 text-center">
  <%= link_to 'Back', tour_members_path(@tour_package.id), :class => "btn btn-primary" %>
</div>

app/views/tour_booking/tour_booker.html.erb
<div class="container tourShow mt-20">
  <p id="notice"><%= notice %></p>

  <% s_point = @tour_package.destinations.find_by_point("Start") %>
  <div class="col-lg-12 col-md-12 col-xs-12 h2 text-center roboto"><%= "#{@tour_package.name}(#{s_point.date if s_point})" %></div>

  <div class="col-lg-12">
  	<%= render :partial => "form1", locals: {:tour_booking => @tour_booking,:tour_package => @tour_package} %>
  </div>

</div>

app/views/tour_booking/tour_confirm.html.erb
<h1>TourBooking#tour_confirm</h1>
<p>Find me in app/views/tour_booking/tour_confirm.html.erb</p>

app/views/tour_booking/tour_members.html.erb
<div class="container tourShow mt-20">
  <p id="notice"><%= notice %></p>

  <% s_point = @tour_package.destinations.find_by_point("Start") %>
  <div class="col-lg-12 col-md-12 col-xs-12 h2 text-center roboto"><%= "#{@tour_package.name}(#{s_point.date if s_point})" %></div>

  <div class="col-lg-12">
    <%= render :partial => "form2", locals: {:tour_booking => @tour_booking,:tour_package => @tour_package} %>
  </div>

</div>