config/routes.rb
Rails.application.routes.draw do
  get 'tour_booking/:tour_package_id/tour_booker' => 'tour_booking#tour_booker', as: :tour_booker

  post 'tour_booking/:tour_package_id/tour_booker' => 'tour_booking#tour_booker_create', as: :tour_booker_create

  get 'tour_booking/:tour_package_id/tour_members' => 'tour_booking#tour_members', as: :tour_members

  post 'tour_booking/:tour_package_id/tour_members' => 'tour_booking#tour_member_create', as: :tour_member_create

  get 'tour_booking/:tour_package_id/tour_confirm' => 'tour_booking#tour_confirm', as: :tour_confirm

  post 'tour_booking/:tour_package_id/tour_confirm' => 'tour_booking#tour_confirm_done', as: :tour_confirm_done

  resources :tour_packages do
  	collection do
  		get "search"
  		get "filter"
  	end
  end
  resources :destinations
  devise_for :users

  authenticated :user do
    root 'tour_packages#index', as: :authenticated_root
  end

  root "tour_packages#index", as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tour_package.rb
class TourPackage < ApplicationRecord
  belongs_to :user
  has_many :destinations
  has_many :tour_bookings

  scope :active, -> { where(active: true) }

  searchkick

  def search_data
  	{
  		name: name
  	}
  end

  include Searchable
end

app/controllers/tour_packages_controller.rb
class TourPackagesController < ApplicationController
  before_action :set_tour_package, only: [:show, :edit, :update, :destroy]
  before_action :find_page, :only => [:search,:filter]
  before_action :collect_destinations, :only => [:index,:filter,:search]

  # GET /tour_packages
  # GET /tour_packages.json
  def index
    @tour_packages = TourPackage.active.paginate(:page => params[:page])
  end

  def search
    @tour_packages = TourPackage.search_tour_pack(params[:q],params[:page])
    render "index"
  end

  def filter
    @tour_packages = TourPackage.filter_tour_pack(params[:source],params[:destination],params[:date],params[:page])
    render "index"
  end

  # GET /tour_packages/1
  # GET /tour_packages/1.json
  def show
  end

  # GET /tour_packages/new
  def new
    @tour_package = TourPackage.new
    respond_to do |format|
      format.js
    end
  end

  # GET /tour_packages/1/edit
  def edit
  end

  # POST /tour_packages
  # POST /tour_packages.json
  def create
    @tour_package = current_user.tour_packages.new(tour_package_params)

    respond_to do |format|
      if @tour_package.save
        if params[:name] and params[:name].any?
          @tour_package.destinations.each do |d|
            d.destroy
          end
          params[:name].each_with_index do |name,i|
            @tour_package.destinations.create(name:name,point:params[:point][i],date:params[:date][i])
          end
        end
        format.html { redirect_to @tour_package, notice: 'Tour package was successfully created.' }
        format.json { render :show, status: :created, location: @tour_package }
      else
        format.html { render :new }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tour_packages/1
  # PATCH/PUT /tour_packages/1.json
  def update
    respond_to do |format|
      if @tour_package.update(tour_package_params)
        if params[:name] and params[:name].any?
          @tour_package.destinations.each do |d|
            d.destroy
          end
          params[:name].each_with_index do |name,i|
            @tour_package.destinations.create(name:name,point:params[:point][i],date:params[:date][i])
          end
        end
        format.html { redirect_to @tour_package, notice: 'Tour package was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour_package }
      else
        format.html { render :edit }
        format.json { render json: @tour_package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tour_packages/1
  # DELETE /tour_packages/1.json
  def destroy
    @tour_package.destroy
    respond_to do |format|
      format.html { redirect_to tour_packages_url, notice: 'Tour package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour_package
      @tour_package = TourPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_package_params
      params.require(:tour_package).permit(:name, :age_from, :age_upto, :max_people, :cost_per_person, :last_submission_date, :active)
    end

    def collect_destinations
      @start_points = Destination.where(point:"Start").collect(&:name).uniq
      @end_points = Destination.where(point:"End").collect(&:name).uniq
      @start_dates = Destination.where(point:"Start").collect(&:date).uniq
    end
end

app/helpers/tour_packages_helper.rb
module TourPackagesHelper

	def display_destinations(ds)
		ds.collect(&:name_date).join(",")
	end
end

app/views/tour_packages/_form.html.erb
<%= form_with(model: tour_package, local: true) do |form| %>
  <div class="step_1">
    <% if tour_package.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tour_package.errors.count, "error") %> prohibited this tour_package from being saved:</h2>

        <ul>
        <% tour_package.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :pack_name %>
      <%= form.text_field :name, id: :tour_package_name, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :age_from %>
      <%= form.number_field :age_from, id: :tour_package_age_from, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :age_upto %>
      <%= form.number_field :age_upto, id: :tour_package_age_upto, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :max_people %>
      <%= form.number_field :max_people, id: :tour_package_max_people, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :cost_per_person %>
      <%= form.text_field :cost_per_person, id: :tour_package_cost_per_person, :class => "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :last_submission_date %>
      <%= form.date_field :last_submission_date, id: :tour_package_last_submission_date, :class => "form-control" %>
    </div>
    <button class="btn btn-default t_next">Save & Continue</button>
  </div>
  <div class="step_2 hidden">
    <div class="dest_list">
      <% tour_package.destinations.each do |destination| %>
        <%= render :partial => "destinations/form", :locals => {:destination => destination} %>
      <% end %>
    </div>
    <div class="form-group text-center">
      <%= link_to "Add Destination", new_destination_path, :remote => true, :class => "btn btn-success" %>
    </div>
    <div class="form-group text-center">
      <%= form.submit "SAVE",:class => "btn btn-primary" %>
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $(".t_next").click(function(){
    c = 0;
    $(".step_1 input").each(function(){
      if ($(this).val() == "") {
        c+=1;
      }
    });
    if (c == 0) {
      $(".step_1").addClass("hidden");
      $(".step_2").removeClass("hidden");
    }
    return false;
  });
  $(document).ready(function() {
    $(document).on("click",".removeParent",function(){
      $(this).closest(".form-inline").remove();
    });
  });
</script>

app/views/tour_packages/_tour_pack_list.html.erb
<% @tour_packages.each do |tour_package| %>
  <div class="tourPack">
    <% if current_user.is_admin? %>
      <div class="pull-right">
        <%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_tour_package_path(tour_package), :remote => true %>
        <%= link_to "<i class='fa fa-close'></i>".html_safe, tour_package, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
    <div class="title text-center h4"><%= tour_package.name.capitalize %>
      <% if tour_package and (b = tour_package.tour_bookings.find_by_user_id(current_user.id)) and b.confirmation %>
        <span style="color:green"><i class='fa fa-check'></i></span>
      <% end %>
    </div>
    <div><label>Places cover:</label> <%= tour_package.destinations.count %></div>
    <div><label>Age Range:</label> <%= "#{tour_package.age_from} - #{tour_package.age_upto}" %></div>
    <div><label>People Limit:</label> <%= tour_package.max_people %></div>
    <div><label>Cost Per Person:</label> Rs.<%= tour_package.cost_per_person.round %></div>
    <div><label>Last Submission Date:</label> <%= tour_package.last_submission_date.strftime("%d %b, %Y") %></div>
    <div class="text-center"><%= link_to 'View Plan', tour_package, :class => "btn btn-success" %></div>
  </div>
<% end %>

app/views/tour_packages/_tour_pack_modal.html.erb
<div id="tourPack" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">New Tour Pack</h4>
      </div>
      <div class="modal-body">
      </div>
    </div>

  </div>
</div>

app/views/tour_packages/edit.html.erb
<h1>Editing Tour Package</h1>

<%= render 'form', tour_package: @tour_package %>

<%= link_to 'Show', @tour_package %> |
<%= link_to 'Back', tour_packages_path %>

app/views/tour_packages/edit.js.erb
$("#tourPack .modal-body").html("<%= escape_javascript(render(:partial => 'form', :locals => {:tour_package => @tour_package})) %>")
$("#tourPack").modal('show');

app/views/tour_packages/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <div class="col-lg-12 col-md-12 col-xs-12 h2 text-center roboto">Welcome to TourPack</div>

  <%#= react_component('TourPack', 
                      {:presenter => @tour_packages.to_json}) %>
  <div class="col-lg-12">
    <% if user_signed_in? %>
      <%= link_to('Logout', destroy_user_session_path, method: :delete, :class => "btn btn-danger pull-right", :style => "margin-left:10px") %>        
    <% end %>
    <% if current_user.is_admin? %>
      <%= link_to "<i class='fa fa-plus'></i> Create Tour Package".html_safe, new_tour_package_path, :remote => true, :class => "btn btn-primary pull-right","data-toggle" => "modal", "data-target" => "#tourPack" %>
    <% end %>
  </div>
  <div class="col-lg-12 col-md-12">
    <div class="searchBox form-inline mt-20 mb-10">
      <%= form_with(url: search_tour_packages_path, :method => :get, local: true, html: {:style => "display: inline-block;width:30%;"}) do |form| %>
        Search <input type="search" name="q" class="form-control" value="<%= params[:q] if params[:q] %>"> <%= "(#{@tour_packages.total_count} matchs)" if action_name == "search" %>
      <% end %>
      <%= form_with(url: filter_tour_packages_path, :method => :get, local: true, html: {:style => "display: inline-block;width:69%;"}) do |form| %>
        <select data-placeholder="Choose a source..." name="source" class="chosen-select">
          <option value=""></option>
          <% @start_points.each do |point| %>
            <option value="<%= point %>"><%= point %></option>
          <% end %>
        </select>
        <select data-placeholder="Choose a destination..." name="destination" class="chosen-select">
          <option value=""></option>
          <% @end_points.each do |point| %>
            <option value="<%= point %>"><%= point %></option>
          <% end %>
        </select>
        <select data-placeholder="Choose a date..." name="date" class="chosen-select">
          <option value=""></option>
          <% @start_dates.each do |date| %>
            <option value="<%= date %>"><%= date %></option>
          <% end %>
        </select>
      <% end %>
    </div>
    <div class="flexContainer">
      <%= render :partial => "tour_pack_list" %>
    </div>
  </div>
  <div class="text-center">
    <%= will_paginate @tour_packages %>
  </div>

  <%= render :partial => "tour_pack_modal" %>
</div>
<script type="text/javascript">
  $(".chosen-select").chosen({width: "30%"});
  <% if params[:source] and (params[:source] != "") %>
    $(".chosen-select[name='source']").val("<%= params[:source] %>").trigger("chosen:updated");
  <% end %>
  <% if params[:destination] and (params[:destination] != "") %>
    $(".chosen-select[name='destination']").val("<%= params[:destination] %>").trigger("chosen:updated");
  <% end %>
  <% if params[:date] and (params[:date] != "") %>
    $(".chosen-select[name='date']").val("<%= params[:date] %>").trigger("chosen:updated");
  <% end %>
  $('.chosen-select').on('change', function(e) {
    $(this).closest("form").submit();
  });
</script>

app/views/tour_packages/new.html.erb
<h1>New Tour Package</h1>

<%= render 'form', tour_package: @tour_package %>

<%= link_to 'Back', tour_packages_path %>

app/views/tour_packages/new.js.erb
$("#tourPack .modal-body").html("<%= escape_javascript(render(:partial => 'form', :locals => {:tour_package => @tour_package})) %>")
$("#tourPack").modal('show');

app/views/tour_packages/show.html.erb
<div class="container tourShow mt-20">
  <p id="notice"><%= notice %></p>

  <div class="col-lg-12 col-md-12 col-xs-12 h2 text-center roboto"><%= @tour_package.name %></div>

  <div class="col-lg-12">
    <div><label>Age Range:</label> <%= "#{@tour_package.age_from} - #{@tour_package.age_upto}" %></div>
  </div>

  <div class="col-lg-12">
    <div><label>Max No of people:</label> <%= @tour_package.max_people %></div>
  </div>

  <div class="col-lg-12">
    <div><label>Cost per person:</label> <%= @tour_package.cost_per_person %></div>
  </div>

  <div class="col-lg-12">
    <div><label>Last submission date:</label> <%= @tour_package.last_submission_date %></div>
  </div>

  <div class="tourPoint col-lg-12 mb-10 mt-10 padding-reset">
    <div class="text-muted h4 col-lg-12">Tour Points</div>
    <% if s_point = @tour_package.destinations.find_by_point("Start") %>
      <div class="col-lg-12">
        <div class="col-lg-12"><label>Start Place:</label> <%= s_point.name_date %></div>
      </div>
    <% end %>
    <% inter_destions = @tour_package.destinations.where(point:"Intermediate").order(date: :asc) %>
    <% if inter_destions.any? %>
      <div class="col-lg-12">
        <div class="col-lg-12"><label>Intermediate Places:</label> <%= display_destinations(inter_destions) %></div>
      </div>
    <% end %>
    <% if e_point = @tour_package.destinations.find_by_point("End") %>
      <div class="col-lg-12">
        <div class="col-lg-12"><label>Destination Place:</label> <%= e_point.name_date %></div>
      </div>
    <% end %>
  </div>

  <div class="col-lg-12 text-center">
    <% if @tour_package and (b = @tour_package.tour_bookings.find_by_user_id(current_user.id)) and b.confirmation %>
      <%= link_to "<i class='fa fa-check'>Booked</i>".html_safe, "#", :class => "btn btn-info" %>
    <% else %>
      <%= link_to 'Book the tour', tour_booker_path(@tour_package.id), :class => "btn btn-success" %>
    <% end %>
    <% if current_user.is_admin? %>
      <%= link_to 'Edit', edit_tour_package_path(@tour_package), :remote => true, :class => "btn btn-primary" %>
    <% end %>
    <%= link_to 'Back', tour_packages_path, :class => "btn btn-primary" %>
  </div>

</div>

<%= render :partial => "tour_pack_modal" %>